/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-07-22 05:13:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    // Check if user is logged in
    String username = (String) session.getAttribute("username");
    if (username == null) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Dashboard - SecureChain</title>\n");
      out.write("    <meta name=\"description\" content=\"SecureChain Dashboard - Manage your secure digital evidence\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            color: #374151;\n");
      out.write("            background: linear-gradient(135deg, #0d9488 0%, #15803d 50%, #0369a1 100%);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            position: relative;\n");
      out.write("            overflow-x: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Animated background particles */\n");
      out.write("        body::before {\n");
      out.write("            content: '';\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            background: url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 1000\"><defs><radialGradient id=\"a\" cx=\"50%\" cy=\"50%\" r=\"50%\"><stop offset=\"0%\" style=\"stop-color:rgba(255,255,255,0.15)\"/><stop offset=\"100%\" style=\"stop-color:rgba(255,255,255,0)\"/></radialGradient></defs><circle cx=\"200\" cy=\"200\" r=\"100\" fill=\"url(%23a)\"/><circle cx=\"800\" cy=\"300\" r=\"150\" fill=\"url(%23a)\"/><circle cx=\"400\" cy=\"700\" r=\"120\" fill=\"url(%23a)\"/><circle cx=\"600\" cy=\"500\" r=\"80\" fill=\"url(%23a)\"/></svg>');\n");
      out.write("            animation: float 20s ease-in-out infinite;\n");
      out.write("            z-index: -1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body::after {\n");
      out.write("            content: '';\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            background: url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 1000\"><defs><linearGradient id=\"b\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\"><stop offset=\"0%\" style=\"stop-color:rgba(255,255,255,0.1)\"/><stop offset=\"100%\" style=\"stop-color:rgba(255,255,255,0.05)\"/></linearGradient></defs><polygon points=\"100,100 200,100 150,50\" fill=\"url(%23b)\"/><polygon points=\"700,200 800,200 750,150\" fill=\"url(%23b)\"/><polygon points=\"300,600 400,600 350,550\" fill=\"url(%23b)\"/></svg>');\n");
      out.write("            animation: geometricFloat 25s ease-in-out infinite reverse;\n");
      out.write("            z-index: -1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes float {\n");
      out.write("            0%, 100% { transform: translateY(0px) rotate(0deg); }\n");
      out.write("            50% { transform: translateY(-20px) rotate(180deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes geometricFloat {\n");
      out.write("            0%, 100% { transform: translateX(0px) rotate(0deg); }\n");
      out.write("            50% { transform: translateX(10px) rotate(90deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes fadeInUp {\n");
      out.write("            from { opacity: 0; transform: translateY(30px); }\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideIn {\n");
      out.write("            from { opacity: 0; transform: translateX(-20px); }\n");
      out.write("            to { opacity: 1; transform: translateX(0); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes pulse {\n");
      out.write("            0%, 100% { transform: scale(1); }\n");
      out.write("            50% { transform: scale(1.05); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Header */\n");
      out.write("        .header {\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\n");
      out.write("            backdrop-filter: blur(20px);\n");
      out.write("            padding: 1.5rem 2rem;\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.3);\n");
      out.write("            position: sticky;\n");
      out.write("            top: 0;\n");
      out.write("            z-index: 100;\n");
      out.write("            animation: slideIn 0.8s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header-content {\n");
      out.write("            max-width: 1400px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #0D9488;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo svg {\n");
      out.write("            width: 2rem;\n");
      out.write("            height: 2rem;\n");
      out.write("            filter: drop-shadow(0 4px 8px rgba(13, 148, 136, 0.3));\n");
      out.write("            animation: pulse 2s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-menu {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 2rem;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item {\n");
      out.write("            color: #374151;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("            padding: 0.5rem 1rem;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item:hover {\n");
      out.write("            background: rgba(13, 148, 136, 0.1);\n");
      out.write("            color: #0D9488;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-item.active {\n");
      out.write("            background: rgba(13, 148, 136, 0.15);\n");
      out.write("            color: #0D9488;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-menu {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-info {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.75rem;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            background: rgba(13, 148, 136, 0.1);\n");
      out.write("            border-radius: 12px;\n");
      out.write("            border: 1px solid rgba(13, 148, 136, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-avatar {\n");
      out.write("            width: 40px;\n");
      out.write("            height: 40px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            background: linear-gradient(135deg, #0d9488, #15803d);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            color: white;\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logout-btn {\n");
      out.write("            padding: 0.75rem 1.5rem;\n");
      out.write("            background: linear-gradient(135deg, #dc2626, #ef4444);\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logout-btn:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 8px 25px rgba(220, 38, 38, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Main Content */\n");
      out.write("        .main-content {\n");
      out.write("            max-width: 1400px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 2rem;\n");
      out.write("            animation: fadeInUp 0.8s ease-out 0.2s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .dashboard-header {\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .dashboard-title {\n");
      out.write("            font-size: 2.5rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: white;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            text-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .dashboard-subtitle {\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            font-weight: 400;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Content Sections */\n");
      out.write("        .content-section {\n");
      out.write("            display: none;\n");
      out.write("            animation: fadeInUp 0.5s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .content-section.active {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Stats Cards */\n");
      out.write("        .stats-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n");
      out.write("            gap: 2rem;\n");
      out.write("            margin-bottom: 3rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card {\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\n");
      out.write("            backdrop-filter: blur(20px);\n");
      out.write("            border-radius: 20px;\n");
      out.write("            padding: 2rem;\n");
      out.write("            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            height: 4px;\n");
      out.write("            background: linear-gradient(135deg, #0d9488, #15803d, #0369a1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 20px 50px rgba(0, 0, 0, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-icon {\n");
      out.write("            width: 50px;\n");
      out.write("            height: 50px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-icon.primary { background: linear-gradient(135deg, #0d9488, #15803d); }\n");
      out.write("        .stat-icon.secondary { background: linear-gradient(135deg, #0369a1, #0d9488); }\n");
      out.write("        .stat-icon.success { background: linear-gradient(135deg, #15803d, #16a34a); }\n");
      out.write("        .stat-icon.warning { background: linear-gradient(135deg, #ea580c, #f59e0b); }\n");
      out.write("\n");
      out.write("        .stat-value {\n");
      out.write("            font-size: 2.5rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #1f2937;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-label {\n");
      out.write("            color: #6b7280;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Action Cards */\n");
      out.write("        .action-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));\n");
      out.write("            gap: 2rem;\n");
      out.write("            margin-bottom: 3rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-card {\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\n");
      out.write("            backdrop-filter: blur(20px);\n");
      out.write("            border-radius: 20px;\n");
      out.write("            padding: 2rem;\n");
      out.write("            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 20px 50px rgba(0, 0, 0, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-header {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 1rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-icon {\n");
      out.write("            width: 60px;\n");
      out.write("            height: 60px;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            background: linear-gradient(135deg, #0d9488, #15803d);\n");
      out.write("            color: white;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-title {\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #1f2937;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-description {\n");
      out.write("            color: #6b7280;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Form Styles */\n");
      out.write("        .form-container {\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\n");
      out.write("            backdrop-filter: blur(20px);\n");
      out.write("            border-radius: 20px;\n");
      out.write("            padding: 2rem;\n");
      out.write("            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #374151;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input[type=\"file\"] {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 1rem;\n");
      out.write("            border: 2px dashed #d1d5db;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            background: #f9fafb;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input[type=\"file\"]:hover {\n");
      out.write("            border-color: #0d9488;\n");
      out.write("            background: rgba(13, 148, 136, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 1.2rem;\n");
      out.write("            background: linear-gradient(135deg, #0d9488 0%, #15803d 50%, #0369a1 100%);\n");
      out.write("            color: white;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: -100%;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\n");
      out.write("            transition: left 0.5s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn:hover::before {\n");
      out.write("            left: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 15px 35px rgba(13, 148, 136, 0.4);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Evidence Table */\n");
      out.write("        .evidence-table {\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\n");
      out.write("            backdrop-filter: blur(20px);\n");
      out.write("            border-radius: 20px;\n");
      out.write("            padding: 2rem;\n");
      out.write("            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\n");
      out.write("            overflow-x: auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .table th,\n");
      out.write("        .table td {\n");
      out.write("            padding: 1rem;\n");
      out.write("            text-align: left;\n");
      out.write("            border-bottom: 1px solid rgba(229, 231, 235, 0.5);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .table th {\n");
      out.write("            background: rgba(249, 250, 251, 0.8);\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #374151;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .table tr:hover {\n");
      out.write("            background: rgba(249, 250, 251, 0.5);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-badge {\n");
      out.write("            padding: 0.25rem 0.75rem;\n");
      out.write("            border-radius: 9999px;\n");
      out.write("            font-size: 0.875rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-verified {\n");
      out.write("            background: #dcfce7;\n");
      out.write("            color: #16a34a;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-pending {\n");
      out.write("            background: #fef3c7;\n");
      out.write("            color: #d97706;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Message Styles */\n");
      out.write("        .message {\n");
      out.write("            padding: 1rem 1.5rem;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .message.success {\n");
      out.write("            background: #dcfce7;\n");
      out.write("            color: #16a34a;\n");
      out.write("            border: 1px solid #bbf7d0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .message.error {\n");
      out.write("            background: #fee2e2;\n");
      out.write("            color: #dc2626;\n");
      out.write("            border: 1px solid #fecaca;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .message.warning {\n");
      out.write("            background: #fef3c7;\n");
      out.write("            color: #d97706;\n");
      out.write("            border: 1px solid #fde68a;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .icon-style {\n");
      out.write("            width: 1.25em;\n");
      out.write("            height: 1.25em;\n");
      out.write("            display: inline-block;\n");
      out.write("            vertical-align: -0.25em;\n");
      out.write("            fill: currentColor;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive Design */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .header-content {\n");
      out.write("                flex-direction: column;\n");
      out.write("                gap: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-menu {\n");
      out.write("                flex-wrap: wrap;\n");
      out.write("                justify-content: center;\n");
      out.write("                gap: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .main-content {\n");
      out.write("                padding: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .dashboard-title {\n");
      out.write("                font-size: 2rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .stats-grid, .action-grid {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* START: Added Modal Styles */\n");
      out.write("        #hashing-info-card {\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .modal {\n");
      out.write("            display: none; /* Hidden by default */\n");
      out.write("            position: fixed;\n");
      out.write("            z-index: 1000;\n");
      out.write("            left: 0;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            overflow: auto;\n");
      out.write("            background-color: rgba(0,0,0,0.6);\n");
      out.write("            backdrop-filter: blur(5px);\n");
      out.write("            animation: fadeIn 0.3s ease-in-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-content {\n");
      out.write("            background-color: #fefefe;\n");
      out.write("            margin: 10% auto;\n");
      out.write("            padding: 2rem 2.5rem;\n");
      out.write("            border: 1px solid #888;\n");
      out.write("            width: 80%;\n");
      out.write("            max-width: 700px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.2);\n");
      out.write("            position: relative;\n");
      out.write("            animation: slideInFromTop 0.4s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-content h2 {\n");
      out.write("            color: #0d9488;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-content h3 {\n");
      out.write("            color: #1f2937;\n");
      out.write("            margin-top: 1.5rem;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            border-bottom: 2px solid #e5e7eb;\n");
      out.write("            padding-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-content p, .modal-content li {\n");
      out.write("            color: #4b5563;\n");
      out.write("            line-height: 1.7;\n");
      out.write("            margin-bottom: 0.75rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .modal-content ul {\n");
      out.write("            list-style-position: inside;\n");
      out.write("            padding-left: 1rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .modal-content li::marker {\n");
      out.write("            color: #0d9488;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .close-btn {\n");
      out.write("            color: #aaa;\n");
      out.write("            float: right;\n");
      out.write("            font-size: 28px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            position: absolute;\n");
      out.write("            top: 15px;\n");
      out.write("            right: 25px;\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .close-btn:hover,\n");
      out.write("        .close-btn:focus {\n");
      out.write("            color: #dc2626;\n");
      out.write("            text-decoration: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @keyframes fadeIn {\n");
      out.write("            from { opacity: 0; }\n");
      out.write("            to { opacity: 1; }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideInFromTop {\n");
      out.write("            from { transform: translateY(-50px); opacity: 0; }\n");
      out.write("            to { transform: translateY(0); opacity: 1; }\n");
      out.write("        }\n");
      out.write("        /* END: Added Modal Styles */\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <div class=\"header-content\">\n");
      out.write("            <div class=\"logo\">\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\" class=\"icon-style\">\n");
      out.write("                    <path fill-rule=\"evenodd\" d=\"M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z\" clip-rule=\"evenodd\" />\n");
      out.write("                </svg>\n");
      out.write("                SecureChain\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <nav class=\"nav-menu\">\n");
      out.write("                <a href=\"#dashboard\" class=\"nav-item active\" onclick=\"showSection('dashboard')\">Dashboard</a>\n");
      out.write("                <a href=\"#upload\" class=\"nav-item\" onclick=\"showSection('upload')\">Upload Evidence</a>\n");
      out.write("                <a href=\"#verify\" class=\"nav-item\" onclick=\"showSection('verify')\">Verify Evidence</a>\n");
      out.write("                <a href=\"#records\" class=\"nav-item\" onclick=\"showSection('records')\">Evidence Records</a>\n");
      out.write("            </nav>\n");
      out.write("            \n");
      out.write("            <div class=\"user-menu\">\n");
      out.write("                <div class=\"user-info\">\n");
      out.write("                    <div class=\"user-avatar\">\n");
      out.write("                        ");
      out.print( username.substring(0, 1).toUpperCase() );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <div style=\"font-weight: 600; color: #1f2937;\">");
      out.print( username );
      out.write("</div>\n");
      out.write("                        <div style=\"font-size: 0.9rem; color: #6b7280;\">Authenticated User Session Lifecycle</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <a href=\"LogoutServlet\" class=\"logout-btn\">\n");
      out.write("                    <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                        <path fill-rule=\"evenodd\" d=\"M3 4.25A2.25 2.25 0 015.25 2h5.5A2.25 2.25 0 0113 4.25v2a.75.75 0 01-1.5 0v-2a.75.75 0 00-.75-.75h-5.5a.75.75 0 00-.75.75v11.5c0 .414.336.75.75.75h5.5a.75.75 0 00.75-.75v-2a.75.75 0 011.5 0v2A2.25 2.25 0 0110.75 18h-5.5A2.25 2.25 0 013 15.75V4.25z\" clip-rule=\"evenodd\" />\n");
      out.write("                        <path fill-rule=\"evenodd\" d=\"M19 10a.75.75 0 00-.75-.75H8.704l1.048-.943a.75.75 0 10-1.004-1.114l-2.5 2.25a.75.75 0 000 1.114l2.5 2.25a.75.75 0 101.004-1.114L8.704 10.75H18.25A.75.75 0 0019 10z\" clip-rule=\"evenodd\" />\n");
      out.write("                    </svg>\n");
      out.write("                    Logout\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <main class=\"main-content\">\n");
      out.write("        <!-- Dashboard Section -->\n");
      out.write("        <div id=\"dashboard\" class=\"content-section active\">\n");
      out.write("            <div class=\"dashboard-header\">\n");
      out.write("                <h1 class=\"dashboard-title\">Dashboard</h1>\n");
      out.write("                <p class=\"dashboard-subtitle\">Welcome back, ");
      out.print( username );
      out.write("! Here's your digital evidence overview.</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");

                // Count total evidence files
                File uploadsDir = new File(application.getRealPath("") + "/uploads");
                int totalFiles = 0;
                if (uploadsDir.exists()) {
                    File[] files = uploadsDir.listFiles();
                    totalFiles = files != null ? files.length : 0;
                }
                
                // Count verified files (files with hash records)
                File hashFile = new File(application.getRealPath("") + "/evidence_hashes.txt");
                int verifiedFiles = 0;
                if (hashFile.exists()) {
                    try (BufferedReader reader = new BufferedReader(new FileReader(hashFile))) {
                        while (reader.readLine() != null) {
                            verifiedFiles++;
                        }
                    } catch (IOException e) {
                        // Handle exception silently in dashboard stats
                    }
                }
            
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"stats-grid\">\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"stat-header\">\n");
      out.write("                        <div class=\"stat-icon primary\">\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M15.988 3.012A2.25 2.25 0 0118 5.25v6.5A2.25 2.25 0 0115.75 14H13.5V7A2.5 2.5 0 0011 4.5H8.128a2.252 2.252 0 011.884-1.488A2.25 2.25 0 0112.25 1h1.5a2.25 2.25 0 012.238 2.012zM11.5 3.25a.75.75 0 01.75-.75h1.5a.75.75 0 01.75.75v.25h-3v-.25z\" clip-rule=\"evenodd\" />\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M2 7a1 1 0 011-1h8a1 1 0 011 1v10a1 1 0 01-1 1H3a1 1 0 01-1-1V7zm2 3.25a.75.75 0 01.75-.75h4.5a.75.75 0 010 1.5h-4.5a.75.75 0 01-.75-.75zm0 3.5a.75.75 0 01.75-.75h4.5a.75.75 0 010 1.5h-4.5a.75.75 0 01-.75-.75z\" clip-rule=\"evenodd\" />\n");
      out.write("                            </svg>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"stat-value\">");
      out.print( totalFiles );
      out.write("</div>\n");
      out.write("                    <div class=\"stat-label\">Total Evidence Files</div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"stat-header\">\n");
      out.write("                        <div class=\"stat-icon success\">\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z\" clip-rule=\"evenodd\" />\n");
      out.write("                            </svg>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"stat-value\">");
      out.print( verifiedFiles );
      out.write("</div>\n");
      out.write("                    <div class=\"stat-label\">Verified Records</div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- START: Modified Card -->\n");
      out.write("                <div class=\"stat-card\" id=\"hashing-info-card\" onclick=\"openModal('sha256Modal')\">\n");
      out.write("                    <div class=\"stat-header\">\n");
      out.write("                        <div class=\"stat-icon secondary\">\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                                <path d=\"M10 2a.75.75 0 01.75.75v.25h.75a.75.75 0 010 1.5h-.75v.25a.75.75 0 01-1.5 0v-.25h-.75a.75.75 0 010-1.5h.75V2.75A.75.75 0 0110 2zM5.05 5.05A.75.75 0 016.11 4.49l.25.433a.75.75 0 01-1.3.75l-.25-.433zM14.95 14.95a.75.75 0 01-.56 1.06l-.433-.25a.75.75 0 01.75-1.3l.433.25a.75.75 0 01.21.99zM5.05 14.95a.75.75 0 01.56-1.06l.433.25a.75.75 0 11-.75 1.3l-.433-.25a.75.75 0 01-.21-.99zM15.51 6.11a.75.75 0 011.06-.56l.433.25a.75.75 0 11-.75 1.3l-.433-.25a.75.75 0 01-.21-.99zM10 8a2 2 0 100 4 2 2 0 000-4zM8.25 10a1.75 1.75 0 113.5 0 1.75 1.75 0 01-3.5 0zM10 18a8 8 0 100-16 8 8 0 000 16z\"/>\n");
      out.write("                            </svg>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"stat-value\">SHA-256</div>\n");
      out.write("                    <div class=\"stat-label\">Hashing Algorithm</div>\n");
      out.write("                </div>\n");
      out.write("                <!-- END: Modified Card -->\n");
      out.write("\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"stat-header\">\n");
      out.write("                        <div class=\"stat-icon warning\">\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z\" clip-rule=\"evenodd\" />\n");
      out.write("                            </svg>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"stat-value\">");
      out.print( totalFiles - verifiedFiles );
      out.write("</div>\n");
      out.write("                    <div class=\"stat-label\">Pending Verification</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"action-grid\">\n");
      out.write("                <div class=\"action-card\" onclick=\"showSection('upload')\">\n");
      out.write("                    <div class=\"action-header\">\n");
      out.write("                        <div class=\"action-icon\">\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                                <path d=\"M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z\" />\n");
      out.write("                            </svg>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"action-title\">Upload Evidence</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"action-description\">\n");
      out.write("                        Upload new digital evidence files to your secure storage. Each file is hashed with SHA-256 for integrity.\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"action-card\" onclick=\"showSection('verify')\">\n");
      out.write("                    <div class=\"action-header\">\n");
      out.write("                        <div class=\"action-icon\">\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M10 1.5A5.5 5.5 0 004.5 7v5.5a5.5 5.5 0 005.5 5.5 5.5 5.5 0 005.5-5.5V7A5.5 5.5 0 0010 1.5zM8.205 10.62a.75.75 0 011.06 0l1.25 1.25a.75.75 0 01-1.06 1.06L8.205 11.68a.75.75 0 010-1.06z\" clip-rule=\"evenodd\" />\n");
      out.write("                            </svg>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"action-title\">Verify Evidence</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"action-description\">\n");
      out.write("                        Check the integrity of an evidence file by comparing its current hash against the stored record.\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"action-card\" onclick=\"showSection('records')\">\n");
      out.write("                    <div class=\"action-header\">\n");
      out.write("                        <div class=\"action-icon\">\n");
      out.write("                           <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                              <path fill-rule=\"evenodd\" d=\"M4.25 2A2.25 2.25 0 002 4.25v11.5A2.25 2.25 0 004.25 18h11.5A2.25 2.25 0 0018 15.75V4.25A2.25 2.25 0 0015.75 2H4.25zm5.78 11.47a.75.75 0 10-1.06-1.06L7.22 14.19l-1.97-1.97a.75.75 0 00-1.06 1.06l2.5 2.5a.75.75 0 001.06 0l3-3zM14 7a.75.75 0 01-.75.75H7a.75.75 0 010-1.5h6.25A.75.75 0 0114 7z\" clip-rule=\"evenodd\" />\n");
      out.write("                           </svg>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"action-title\">View Records</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"action-description\">\n");
      out.write("                        Browse all uploaded evidence files and view their verification status and details.\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Upload Section -->\n");
      out.write("        <div id=\"upload\" class=\"content-section\">\n");
      out.write("            <div class=\"dashboard-header\">\n");
      out.write("                <h1 class=\"dashboard-title\">Upload Evidence</h1>\n");
      out.write("                <p class=\"dashboard-subtitle\">Securely upload a new evidence file. A SHA-256 hash will be generated and stored.</p>\n");
      out.write("            </div>\n");
      out.write("            ");

                String uploadStatus = (String) request.getAttribute("uploadStatus");
                if (uploadStatus != null) {
                    if (uploadStatus.startsWith("Success")) {
            
      out.write("\n");
      out.write("                        <div class=\"message success\">\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.236 4.53L7.53 9.53a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z\" clip-rule=\"evenodd\" /></svg>\n");
      out.write("                            ");
      out.print( uploadStatus );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("            ");
      } else { 
      out.write("\n");
      out.write("                        <div class=\"message error\">\n");
      out.write("                           <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z\" clip-rule=\"evenodd\" /></svg>\n");
      out.write("                            ");
      out.print( uploadStatus );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("            ");
      }
                }
            
      out.write("\n");
      out.write("            <div class=\"form-container\">\n");
      out.write("                <form action=\"UploadServlet\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"evidenceFile\">Select Evidence File</label>\n");
      out.write("                        <input type=\"file\" id=\"evidenceFile\" name=\"evidenceFile\" required>\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" class=\"submit-btn\">\n");
      out.write("                        <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M9.25 13.25a.75.75 0 001.5 0V4.636l2.955 3.129a.75.75 0 001.09-1.03l-4.25-4.5a.75.75 0 00-1.09 0l-4.25 4.5a.75.75 0 101.09 1.03L9.25 4.636v8.614z\" /><path d=\"M3.5 12.75a.75.75 0 00-1.5 0v2.5A2.75 2.75 0 004.75 18h10.5A2.75 2.75 0 0018 15.25v-2.5a.75.75 0 00-1.5 0v2.5c0 .69-.56 1.25-1.25 1.25H4.75c-.69 0-1.25-.56-1.25-1.25v-2.5z\" /></svg>\n");
      out.write("                        Upload and Secure\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Verify Section -->\n");
      out.write("        <div id=\"verify\" class=\"content-section\">\n");
      out.write("            <div class=\"dashboard-header\">\n");
      out.write("                <h1 class=\"dashboard-title\">Verify Evidence</h1>\n");
      out.write("                <p class=\"dashboard-subtitle\">Upload a file to check its integrity against the stored hash records.</p>\n");
      out.write("            </div>\n");
      out.write("            ");

                String verificationResult = (String) request.getAttribute("verificationResult");
                if (verificationResult != null) {
                    String verificationMessage = (String) request.getAttribute("verificationMessage");
                    String messageClass = "warning";
                    String iconPath = "<path fill-rule='evenodd' d='M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z' clip-rule='evenodd' />";
                    if ("valid".equals(verificationResult)) {
                        messageClass = "success";
                        iconPath = "<path fill-rule='evenodd' d='M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.236 4.53L7.53 9.53a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z' clip-rule='evenodd' />";
                    } else if ("invalid".equals(verificationResult)) {
                        messageClass = "error";
                    } else { // notfound
                        iconPath = "<path fill-rule='evenodd' d='M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z' clip-rule='evenodd' />";
                    }
            
      out.write("\n");
      out.write("                    <div class=\"message ");
      out.print( messageClass );
      out.write("\">\n");
      out.write("                        <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">");
      out.print( iconPath );
      out.write("</svg>\n");
      out.write("                        ");
      out.print( verificationMessage );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("            ");
  } 
      out.write("\n");
      out.write("            <div class=\"form-container\">\n");
      out.write("                <form action=\"VerifyServlet\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"verifyFile\">Select File to Verify</label>\n");
      out.write("                        <input type=\"file\" id=\"verifyFile\" name=\"verifyFile\" required>\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" class=\"submit-btn\">\n");
      out.write("                        <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M10 1.5A5.5 5.5 0 004.5 7v5.5a5.5 5.5 0 005.5 5.5 5.5 5.5 0 005.5-5.5V7A5.5 5.5 0 0010 1.5zM8.205 10.62a.75.75 0 011.06 0l1.25 1.25a.75.75 0 01-1.06 1.06L8.205 11.68a.75.75 0 010-1.06z\" clip-rule=\"evenodd\" /></svg>\n");
      out.write("                        Verify Integrity\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Evidence Records Section -->\n");
      out.write("        <div id=\"records\" class=\"content-section\">\n");
      out.write("            <div class=\"dashboard-header\">\n");
      out.write("                <h1 class=\"dashboard-title\">Evidence Records</h1>\n");
      out.write("                <p class=\"dashboard-subtitle\">A complete log of all uploaded evidence and their verification status.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"evidence-table\">\n");
      out.write("                <table class=\"table\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>File Name</th>\n");
      out.write("                            <th>Stored Hash (SHA-256)</th>\n");
      out.write("                            <th>Status</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        ");

                            String recordsHashFilePath = application.getRealPath("") + "/evidence_hashes.txt";
                            File recordsHashFile = new File(recordsHashFilePath);
                            Map<String, String> evidenceMap = new HashMap<>();
                            boolean hasEvidence = false;

                            if (recordsHashFile.exists()) {
                                try (BufferedReader reader = new BufferedReader(new FileReader(recordsHashFile))) {
                                    String line;
                                    while ((line = reader.readLine()) != null) {
                                        String[] parts = line.split(":", 2);
                                        if (parts.length == 2) {
                                            evidenceMap.put(parts[0].trim(), parts[1].trim());
                                        }
                                    }
                                } catch (IOException e) {
                                    out.println("<tr><td colspan='3' class='message error'>Error reading hash file: " + e.getMessage() + "</td></tr>");
                                }
                            }

                            // Display verified records
                            for (Map.Entry<String, String> entry : evidenceMap.entrySet()) {
                                hasEvidence = true;
                        
      out.write("\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>");
      out.print( entry.getKey() );
      out.write("</td>\n");
      out.write("                                    <td><code style=\"font-size: 0.9em;\">");
      out.print( entry.getValue() );
      out.write("</code></td>\n");
      out.write("                                    <td><span class=\"status-badge status-verified\">Verified</span></td>\n");
      out.write("                                </tr>\n");
      out.write("                        ");

                            }

                            // Check for files in uploads dir that are not in the hash map (pending)
                            File recordsUploadsDir = new File(application.getRealPath("") + "/uploads");
                            if (recordsUploadsDir.exists() && recordsUploadsDir.isDirectory()) {
                                File[] uploadedFiles = recordsUploadsDir.listFiles();
                                if (uploadedFiles != null) {
                                    for (File file : uploadedFiles) {
                                        if (!evidenceMap.containsKey(file.getName())) {
                                            hasEvidence = true;
                        
      out.write("\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>");
      out.print( file.getName() );
      out.write("</td>\n");
      out.write("                                                <td>-</td>\n");
      out.write("                                                <td><span class=\"status-badge status-pending\">Pending</span></td>\n");
      out.write("                                            </tr>\n");
      out.write("                        ");

                                        }
                                    }
                                }
                            }

                            if (!hasEvidence) {
                        
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td colspan=\"3\" style=\"text-align: center; padding: 2rem; color: #6b7280;\">No evidence files found. <a href=\"#upload\" onclick=\"showSection('upload')\" style=\"color: #0d9488; font-weight: 500;\">Upload one now</a>.</td>\n");
      out.write("                            </tr>\n");
      out.write("                        ");

                            }
                        
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("    \n");
      out.write("    <!-- START: Added Modal HTML -->\n");
      out.write("    <div id=\"sha256Modal\" class=\"modal\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <span class=\"close-btn\" onclick=\"closeModal('sha256Modal')\">×</span>\n");
      out.write("            <h2>What is SHA-256?</h2>\n");
      out.write("            <p>SHA-256 (Secure Hash Algorithm 256-bit) is a cryptographic hash function. It takes any input (like a file) and produces a fixed-size 256-bit (64-character hexadecimal) string known as a \"hash\" or \"digest\". This hash is a unique digital fingerprint of the data.</p>\n");
      out.write("            <h3>Key Characteristics:</h3>\n");
      out.write("            <ul>\n");
      out.write("                <li><strong>Deterministic:</strong> The same file will always produce the exact same SHA-256 hash.</li>\n");
      out.write("                <li><strong>One-Way Function:</strong> It is computationally impossible to reverse the process and get the original file from its hash.</li>\n");
      out.write("                <li><strong>Avalanche Effect:</strong> Changing even a single bit in the file will result in a completely different and unpredictable hash.</li>\n");
      out.write("                <li><strong>Collision Resistant:</strong> It's virtually impossible to find two different files that produce the same hash.</li>\n");
      out.write("            </ul>\n");
      out.write("            <h3>Why is it used in SecureChain?</h3>\n");
      out.write("            <p>We use SHA-256 to guarantee the integrity of your evidence. When you upload a file, we calculate its hash and store it securely. To verify the file later, we simply recalculate the hash of the current file and compare it to the original, stored hash. If they match, it proves the file has not been altered, tampered with, or corrupted in any way. This provides a robust and mathematically certain method for maintaining the chain of custody for digital evidence.</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- END: Added Modal HTML -->\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        // START: Added Modal Functions\n");
      out.write("        function openModal(modalId) {\n");
      out.write("            const modal = document.getElementById(modalId);\n");
      out.write("            if (modal) {\n");
      out.write("                modal.style.display = 'block';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function closeModal(modalId) {\n");
      out.write("            const modal = document.getElementById(modalId);\n");
      out.write("            if (modal) {\n");
      out.write("                modal.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Close modal when clicking on the background overlay\n");
      out.write("        window.addEventListener('click', function(event) {\n");
      out.write("            const modal = document.getElementById('sha256Modal');\n");
      out.write("            if (event.target == modal) {\n");
      out.write("                closeModal('sha256Modal');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("        // END: Added Modal Functions\n");
      out.write("\n");
      out.write("        function showSection(sectionId) {\n");
      out.write("            document.querySelectorAll('.content-section').forEach(section => {\n");
      out.write("                section.classList.remove('active');\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            const targetSection = document.getElementById(sectionId);\n");
      out.write("            if (targetSection) {\n");
      out.write("                targetSection.classList.add('active');\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            document.querySelectorAll('.nav-item').forEach(item => {\n");
      out.write("                item.classList.remove('active');\n");
      out.write("            });\n");
      out.write("            const activeNavItem = document.querySelector(`.nav-item[href=\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sectionId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"]`);\n");
      out.write("            if(activeNavItem) {\n");
      out.write("                activeNavItem.classList.add('active');\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            if(history.pushState) {\n");
      out.write("                history.pushState(null, null, window.location.pathname + '#' + sectionId);\n");
      out.write("            } else {\n");
      out.write("                window.location.hash = '#' + sectionId;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        document.addEventListener('DOMContentLoaded', () => {\n");
      out.write("            let initialSection = 'dashboard';\n");
      out.write("            const hash = window.location.hash.substring(1);\n");
      out.write("            if (hash) {\n");
      out.write("                initialSection = hash;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            ");
 if (request.getAttribute("uploadStatus") != null) { 
      out.write("\n");
      out.write("                initialSection = 'upload';\n");
      out.write("            ");
 } else if (request.getAttribute("verificationResult") != null) { 
      out.write("\n");
      out.write("                initialSection = 'verify';\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            showSection(initialSection);\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
