/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-07-22 05:09:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>SecureChain - Digital Evidence Management Solutions</title>\n");
      out.write("    <meta name=\"description\" content=\"Professional digital evidence management system with blockchain-grade security, SHA-256 verification, and comprehensive audit trails.\">\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            color: #374151;\n");
      out.write("            overflow-x: hidden;\n");
      out.write("            background-color: #f9fafb; /* Set a base background */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* --- Class for SVG Icons --- */\n");
      out.write("        .icon-style {\n");
      out.write("            width: 1.25em; /* Slightly larger for better visibility */\n");
      out.write("            height: 1.25em;\n");
      out.write("            display: inline-block;\n");
      out.write("            vertical-align: -0.25em; /* Better alignment with text */\n");
      out.write("            fill: currentColor;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Navigation */\n");
      out.write("        .navbar {\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\n");
      out.write("            backdrop-filter: blur(20px);\n");
      out.write("            z-index: 1000;\n");
      out.write("            padding: 1rem 0;\n");
      out.write("            box-shadow: 0 2px 20px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-container {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 0 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo {\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #0D9488;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-links {\n");
      out.write("            display: flex;\n");
      out.write("            list-style: none;\n");
      out.write("            gap: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-links a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: #374151;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav-links a:hover {\n");
      out.write("            color: #0D9488;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Hero Section */\n");
      out.write("        .hero {\n");
      out.write("            background: linear-gradient(135deg, #0d9488 0%, #15803d 100%);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            background: url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 1000\"><defs><radialGradient id=\"a\" cx=\"50%\" cy=\"50%\" r=\"50%\"><stop offset=\"0%\" style=\"stop-color:rgba(255,255,255,0.1)\"/><stop offset=\"100%\" style=\"stop-color:rgba(255,255,255,0)\"/></radialGradient></defs><circle cx=\"200\" cy=\"200\" r=\"100\" fill=\"url(%23a)\"/><circle cx=\"800\" cy=\"300\" r=\"150\" fill=\"url(%23a)\"/><circle cx=\"400\" cy=\"700\" r=\"120\" fill=\"url(%23a)\"/></svg>');\n");
      out.write("            animation: float 20s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes float {\n");
      out.write("            0%, 100% { transform: translateY(0px) rotate(0deg); }\n");
      out.write("            50% { transform: translateY(-20px) rotate(180deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-content {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 0 2rem;\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 1fr;\n");
      out.write("            gap: 4rem;\n");
      out.write("            align-items: center;\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-text h1 {\n");
      out.write("            font-size: 3.5rem;\n");
      out.write("            font-weight: 800;\n");
      out.write("            color: white;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            line-height: 1.2;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-text .subtitle {\n");
      out.write("            font-size: 1.3rem;\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-text p {\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\n");
      out.write("            margin-bottom: 2.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-buttons {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 1rem;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn {\n");
      out.write("            padding: 1rem 2rem;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 50px;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.75rem; /* Increased gap for icons */\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\n");
      out.write("            color: white;\n");
      out.write("            border: 2px solid rgba(255, 255, 255, 0.3);\n");
      out.write("            backdrop-filter: blur(10px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background: rgba(255, 255, 255, 0.3);\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background: white;\n");
      out.write("            color: #0D9488;\n");
      out.write("            border: 2px solid white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background: transparent;\n");
      out.write("            color: white;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Sections */\n");
      out.write("        .features, .solutions, .tech-stack, .contact, .footer {\n");
      out.write("            padding: 8rem 0;\n");
      out.write("        }\n");
      out.write("        .features { background: white; }\n");
      out.write("        .solutions { background: #111827; color: #e5e7eb; }\n");
      out.write("        .tech-stack { background: #f9fafb; }\n");
      out.write("        .contact { background: white; }\n");
      out.write("        .footer { background: #111827; color: #d1d5db; padding: 5rem 0 2rem; }\n");
      out.write("\n");
      out.write("        .section-container { max-width: 1200px; margin: 0 auto; padding: 0 2rem; }\n");
      out.write("        .section-header { text-align: center; margin-bottom: 5rem; }\n");
      out.write("        .section-header h2 { font-size: 2.5rem; font-weight: 700; color: #1f2937; margin-bottom: 1rem; }\n");
      out.write("        .section-header p { font-size: 1.1rem; color: #6b7280; max-width: 700px; margin: 0 auto; }\n");
      out.write("        \n");
      out.write("        .solutions .section-header h2 { color: white; }\n");
      out.write("        .solutions .section-header p { color: #d1d5db; }\n");
      out.write("        \n");
      out.write("        /* Grid & Card Styles */\n");
      out.write("        .features-grid, .solutions-grid, .tech-grid {\n");
      out.write("            display: grid;\n");
      out.write("            gap: 2rem;\n");
      out.write("        }\n");
      out.write("        .features-grid { grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); }\n");
      out.write("        .solutions-grid { grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); gap: 3rem; margin-top: 4rem; }\n");
      out.write("        \n");
      out.write("        .feature-card { \n");
      out.write("            text-align: center; \n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            background: #f9fafb;\n");
      out.write("            padding: 2.5rem; \n");
      out.write("            border-radius: 20px; \n");
      out.write("            border: 1px solid #e5e7eb;\n");
      out.write("        }\n");
      out.write("        .feature-card:hover { \n");
      out.write("            transform: translateY(-10px); \n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.08); \n");
      out.write("            border-color: #0D9488;\n");
      out.write("            background-color: white;\n");
      out.write("        }\n");
      out.write("        .feature-icon { font-size: 3rem; margin-bottom: 1.5rem; display: block; color: #0D9488; }\n");
      out.write("        .feature-card h3 { font-size: 1.3rem; font-weight: 600; color: #1f2937; margin-bottom: 1rem; }\n");
      out.write("        .feature-card p { color: #6b7280; line-height: 1.6; }\n");
      out.write("\n");
      out.write("        .solution-card { background: rgba(255, 255, 255, 0.05); backdrop-filter: blur(10px); padding: 2.5rem; border-radius: 20px; border: 1px solid rgba(255, 255, 255, 0.1); transition: all 0.3s ease; }\n");
      out.write("        .solution-card:hover { transform: translateY(-5px); background: rgba(255, 255, 255, 0.08); }\n");
      out.write("        .solution-card h3 { font-size: 1.3rem; margin-bottom: 1rem; color: white; display: flex; align-items: center; gap: 0.75rem; }\n");
      out.write("        .solution-card ul { list-style: none; margin-top: 1rem; padding-left: 0; }\n");
      out.write("        .solution-card li { padding: 0.5rem 0 0.5rem 1.5rem; position: relative; }\n");
      out.write("        .solution-card li:before { content: '?'; position: absolute; left: 0; color: #4ade80; font-weight: bold; }\n");
      out.write("\n");
      out.write("        /* Technology Stack Section */\n");
      out.write("        .tech-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n");
      out.write("            gap: 2rem;\n");
      out.write("            margin-top: 4rem;\n");
      out.write("        }\n");
      out.write("        .tech-card {\n");
      out.write("            background: white;\n");
      out.write("            padding: 2.5rem 2rem;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            text-align: center;\n");
      out.write("            border: 1px solid #e5e7eb;\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.04);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .tech-card:hover {\n");
      out.write("            transform: translateY(-8px);\n");
      out.write("            box-shadow: 0 15px 30px rgba(13, 148, 136, 0.12);\n");
      out.write("            border-color: #0D9488;\n");
      out.write("        }\n");
      out.write("        .tech-icon {\n");
      out.write("            font-size: 3rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            color: #0D9488;\n");
      out.write("            line-height: 1; /* Fixes SVG vertical alignment issues */\n");
      out.write("        }\n");
      out.write("        .tech-card h3 {\n");
      out.write("            font-size: 1.3rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #1f2937;\n");
      out.write("            margin-bottom: 0.75rem;\n");
      out.write("        }\n");
      out.write("        .tech-card p {\n");
      out.write("            color: #6b7280;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Contact Section */\n");
      out.write("        .contact-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 1.2fr; /* Give more space to the form */\n");
      out.write("            gap: 4rem;\n");
      out.write("            align-items: flex-start;\n");
      out.write("        }\n");
      out.write("        .contact-info h3 {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            color: #1f2937;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("        }\n");
      out.write("        .contact-info p {\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("            color: #6b7280;\n");
      out.write("        }\n");
      out.write("        .contact-details-list {\n");
      out.write("            list-style: none;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("        .contact-details-list li {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: flex-start; /* Align icon to top of text */\n");
      out.write("            gap: 1rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            font-size: 1rem;\n");
      out.write("        }\n");
      out.write("        .contact-details-list .icon-style {\n");
      out.write("            color: #0D9488;\n");
      out.write("            width: 1.5rem;\n");
      out.write("            height: 1.5rem;\n");
      out.write("            flex-shrink: 0; /* Prevent icon from shrinking */\n");
      out.write("            margin-top: 0.15em;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .contact-form {\n");
      out.write("            background: white;\n");
      out.write("            padding: 2.5rem;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.07);\n");
      out.write("        }\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #374151;\n");
      out.write("        }\n");
      out.write("        .form-group input,\n");
      out.write("        .form-group textarea {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.8rem 1rem;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            border: 1px solid #d1d5db;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-family: inherit;\n");
      out.write("            transition: border-color 0.3s, box-shadow 0.3s;\n");
      out.write("        }\n");
      out.write("        .form-group input:focus,\n");
      out.write("        .form-group textarea:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: #0D9488;\n");
      out.write("            box-shadow: 0 0 0 3px rgba(13, 148, 136, 0.2);\n");
      out.write("        }\n");
      out.write("        .form-group textarea {\n");
      out.write("            resize: vertical;\n");
      out.write("            min-height: 120px;\n");
      out.write("        }\n");
      out.write("        .submit-btn {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 1rem;\n");
      out.write("            background-color: #0D9488;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.3s, transform 0.2s;\n");
      out.write("        }\n");
      out.write("        .submit-btn:hover {\n");
      out.write("            background-color: #0f766e;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Footer */\n");
      out.write("        .footer-content { max-width: 1200px; margin: 0 auto; padding: 0 2rem; display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 3rem; }\n");
      out.write("        .footer-section p { color: #9ca3af; }\n");
      out.write("        .footer-section h3 { margin-bottom: 1.5rem; color: #0D9488; font-size: 1.1rem;}\n");
      out.write("        .footer-section ul { list-style: none; padding-left: 0; }\n");
      out.write("        .footer-section li { margin-bottom: 0.75rem; }\n");
      out.write("        .footer-section a, .footer-section .contact-link { color: #9ca3af; text-decoration: none; transition: color 0.3s ease; display: flex; align-items: center; gap: 0.5rem; }\n");
      out.write("        .footer-section a:hover { color: white; }\n");
      out.write("        .footer-bottom { text-align: center; padding-top: 3rem; margin-top: 3rem; border-top: 1px solid #374151; color: #9ca3af; }\n");
      out.write("\n");
      out.write("        /* Responsive Design */\n");
      out.write("        @media (max-width: 992px) {\n");
      out.write("            .contact-grid {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .navbar { padding: 0.5rem 0; }\n");
      out.write("            .nav-container { padding: 0 1rem; }\n");
      out.write("            .nav-links { display: none; }\n");
      out.write("            .hero-content { grid-template-columns: 1fr; gap: 2rem; padding: 8rem 1rem 2rem; text-align: center; }\n");
      out.write("            .hero-text h1 { font-size: 2.5rem; }\n");
      out.write("            .hero-buttons { justify-content: center; }\n");
      out.write("            .section-container { padding: 0 1rem; }\n");
      out.write("            .section-header h2 { font-size: 2rem; }\n");
      out.write("            .features-grid, .solutions-grid, .tech-grid { grid-template-columns: 1fr; }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Scroll animations */\n");
      out.write("        .fade-in { opacity: 0; transform: translateY(30px); transition: all 0.6s ease; }\n");
      out.write("        .fade-in.visible { opacity: 1; transform: translateY(0); }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("        <div class=\"nav-container\">\n");
      out.write("            <a href=\"#\" class=\"logo\">\n");
      out.write("                <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\" style=\"width:1.2em; height:1.2em;\"><path fill-rule=\"evenodd\" d=\"M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z\" clip-rule=\"evenodd\" /></svg>\n");
      out.write("                SecureChain\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"nav-links\">\n");
      out.write("                <li><a href=\"#home\">Home</a></li>\n");
      out.write("                <li><a href=\"#features\">Features</a></li>\n");
      out.write("                <li><a href=\"#solutions\">Solutions</a></li>\n");
      out.write("                <li><a href=\"#technology\">Technology</a></li>\n");
      out.write("                <li><a href=\"#contact\">Contact</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Hero Section -->\n");
      out.write("    <section class=\"hero\" id=\"home\">\n");
      out.write("        <div class=\"hero-content\">\n");
      out.write("             <div class=\"hero-text\">\n");
      out.write("                <h1>Secure Digital Evidence Management</h1>\n");
      out.write("                <p class=\"subtitle\">Blockchain-grade security for forensic professionals</p>\n");
      out.write("                <p>Protect, verify, and manage digital evidence with military-grade encryption, immutable audit trails, and comprehensive chain-of-custody tracking.</p>\n");
      out.write("                <div class=\"hero-buttons\">\n");
      out.write("                    <a href=\"register.jsp\" class=\"btn btn-primary\">\n");
      out.write("                        <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z\" /></svg>\n");
      out.write("                        Start Free Trial\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"#contact\" class=\"btn btn-secondary\">\n");
      out.write("                        <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M2 3.5A1.5 1.5 0 013.5 2h1.148a1.5 1.5 0 011.465 1.175l.716 3.578a1.5 1.5 0 01-1.305 1.762l-1.104.442a1.5 1.5 0 00-1.07 2.13l3.293 3.293a1.5 1.5 0 002.13-1.07l.442-1.104a1.5 1.5 0 011.762-1.305l3.578.716A1.5 1.5 0 0118 15.352V16.5a1.5 1.5 0 01-1.5 1.5h-10A1.5 1.5 0 015 16.5v-3.865a1.5 1.5 0 01.358-1.002l.49-1.225L4.05 9.174A1.5 1.5 0 012 7.71V3.5z\" /></svg>\n");
      out.write("                        Request Demo\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("             <div class=\"hero-visual\">\n");
      out.write("                <!-- Dashboard content could go here if needed -->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Features Section -->\n");
      out.write("    <section class=\"features\" id=\"features\">\n");
      out.write("        <div class=\"section-container\">\n");
      out.write("            <div class=\"section-header fade-in\">\n");
      out.write("                <h2>Advanced Security Features</h2>\n");
      out.write("                <p>Comprehensive digital evidence management with enterprise-grade security and forensic-ready documentation.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"features-grid\">\n");
      out.write("                <div class=\"feature-card fade-in\">\n");
      out.write("                    <div class=\"feature-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H4.5a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z\" /></svg></div>\n");
      out.write("                    <h3>Multi-Layer Authentication</h3>\n");
      out.write("                    <p>Advanced role-based access control with biometric authentication, multi-factor verification, and session management.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card fade-in\">\n");
      out.write("                    <div class=\"feature-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z\" /></svg></div>\n");
      out.write("                    <h3>SHA-256 Hash Verification</h3>\n");
      out.write("                    <p>Automatic cryptographic hash generation and verification ensures file integrity and provides tamper-evident proof.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card fade-in\">\n");
      out.write("                    <div class=\"feature-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M7.5 14.25v2.25m3-4.5v4.5m3-6.75v6.75m3-9v9M6 20.25h12A2.25 2.25 0 0020.25 18V6A2.25 2.25 0 0018 3.75H6A2.25 2.25 0 003.75 6v12A2.25 2.25 0 006 20.25z\" /></svg></div>\n");
      out.write("                    <h3>Immutable Audit Trail</h3>\n");
      out.write("                    <p>Complete chain-of-custody tracking with timestamped logs, user actions, and metadata preservation for compliance.</p>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"feature-card fade-in\">\n");
      out.write("                    <div class=\"feature-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 16.5V9.75m0 0l-3 3m3-3l3 3M6.75 19.5a4.5 4.5 0 01-1.41-8.775 5.25 5.25 0 0110.233-2.33 3 3 0 013.758 3.848A3.752 3.752 0 0118 19.5H6.75z\" /></svg></div>\n");
      out.write("                    <h3>Hybrid Cloud Storage</h3>\n");
      out.write("                    <p>Secure cloud-based storage with local backup options, automated redundancy, and enterprise-grade encryption.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card fade-in\">\n");
      out.write("                    <div class=\"feature-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0\" /></svg></div>\n");
      out.write("                    <h3>Real-time Monitoring</h3>\n");
      out.write("                    <p>24/7 system monitoring with instant alerts for unauthorized access attempts, system anomalies, and security breaches.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card fade-in\">\n");
      out.write("                    <div class=\"feature-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M10.5 1.5H8.25A2.25 2.25 0 006 3.75v16.5a2.25 2.25 0 002.25 2.25h7.5A2.25 2.25 0 0018 20.25V3.75a2.25 2.25 0 00-2.25-2.25H13.5m-3 0V3h3V1.5m-3 0h3m-3 18.75h3\" /></svg></div>\n");
      out.write("                    <h3>Mobile Accessibility</h3>\n");
      out.write("                    <p>Secure mobile applications for field evidence collection, real-time verification, and remote access with top security.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Solutions Section -->\n");
      out.write("    <section class=\"solutions\" id=\"solutions\">\n");
      out.write("        <div class=\"section-container\">\n");
      out.write("            <div class=\"section-header fade-in\">\n");
      out.write("                <h2 style=\"color: white;\">Industry Solutions</h2>\n");
      out.write("                <p>Tailored digital evidence management for various sectors and use cases.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"solutions-grid\">\n");
      out.write("                <div class=\"solution-card fade-in\">\n");
      out.write("                    <h3><svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M4 2a1 1 0 011 1v1h1a1 1 0 010 2H5v1h1a1 1 0 110 2H5v1h1a1 1 0 110 2H5v1h1a1 1 0 110 2H5v1a1 1 0 01-2 0V3a1 1 0 011-1zm11 1h-2a1 1 0 00-1 1v11a1 1 0 001 1h2a1 1 0 001-1V4a1 1 0 00-1-1z\" clip-rule=\"evenodd\" /></svg> Law Enforcement</h3>\n");
      out.write("                    <p>Comprehensive evidence management for police departments, detective units, and investigative agencies.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"solution-card fade-in\">\n");
      out.write("                    <h3><svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M10.53 2.47a.75.75 0 010 1.06l-4.72 4.72h10.44a.75.75 0 010 1.5H5.81l4.72 4.72a.75.75 0 11-1.06 1.06l-6-6a.75.75 0 010-1.06l6-6a.75.75 0 011.06 0zM16.25 5h.75a.75.75 0 010 1.5h-.75a.75.75 0 010-1.5z\" clip-rule=\"evenodd\" /></svg> Legal Firms</h3>\n");
      out.write("                    <p>Secure evidence management for law firms, corporate legal departments, and litigation support.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"solution-card fade-in\">\n");
      out.write("                    <h3><svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M3.5 2A1.5 1.5 0 002 3.5v1.256a1.5 1.5 0 00.124.62l3.36 6.719A1.5 1.5 0 007 13h6a1.5 1.5 0 001.516-1.105l2.067-6.202A1.5 1.5 0 0015.067 4H10V3.5A1.5 1.5 0 008.5 2h-5z\" /><path d=\"M4 14a1 1 0 112 0 1 1 0 01-2 0zM14 14a1 1 0 112 0 1 1 0 01-2 0z\" /></svg> Corporate Security</h3>\n");
      out.write("                    <p>Enterprise-grade security for internal investigations and incident response teams.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"solution-card fade-in\">\n");
      out.write("                    <h3><svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M4.632 3.335A5.352 5.352 0 0110 5.25c2.196 0 4.113 1.28 4.965 3.123A5.352 5.352 0 0115.368 16.665 5.352 5.352 0 0110 14.75c-2.196 0-4.113-1.28-4.965-3.123A5.352 5.352 0 014.632 3.335z\" /><path d=\"M10 12.25a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z\" /></svg> Digital Forensics</h3>\n");
      out.write("                    <p>Specialized tools for forensic investigators and cybersecurity professionals.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Technology Stack Section -->\n");
      out.write("    <section class=\"tech-stack\" id=\"technology\">\n");
      out.write("        <div class=\"section-container\">\n");
      out.write("            <div class=\"section-header fade-in\">\n");
      out.write("                <h2>Our Technology Stack</h2>\n");
      out.write("                <p>We leverage a robust, modern technology stack to deliver unparalleled security, scalability, and performance for your critical digital evidence.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"tech-grid\">\n");
      out.write("                <div class=\"tech-card fade-in\">\n");
      out.write("                    <div class=\"tech-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 15\" /></svg></div>\n");
      out.write("                    <h3>Backend Framework</h3>\n");
      out.write("                    <p>Powered by Java Enterprise (JSP/Servlet) and the Spring Framework for mission-critical reliability and performance.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"tech-card fade-in\">\n");
      out.write("                    <div class=\"tech-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.57-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.286zm0 13.036h.008v.008h-.008v-.008z\" /></svg></div>\n");
      out.write("                    <h3>Military-Grade Encryption</h3>\n");
      out.write("                    <p>AES-256 for data at rest and in transit, complemented by SHA-256 hashing and a robust PKI infrastructure.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"tech-card fade-in\">\n");
      out.write("                    <div class=\"tech-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M20.25 6.375c0 2.278-3.694 4.125-8.25 4.125S3.75 8.653 3.75 6.375m16.5 0c0-2.278-3.694-4.125-8.25-4.125S3.75 4.097 3.75 6.375m16.5 0v11.25c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125V6.375\" /></svg></div>\n");
      out.write("                    <h3>Database Systems</h3>\n");
      out.write("                    <p>Enterprise-grade MySQL and PostgreSQL with clustering, replication, and automated backup for ultimate data integrity.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"tech-card fade-in\">\n");
      out.write("                    <div class=\"tech-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244\" /></svg></div>\n");
      out.write("                    <h3>Blockchain Ledger</h3>\n");
      out.write("                    <p>Private blockchain integration (Hyperledger Fabric) to create an immutable, tamper-proof audit trail for every action.</p>\n");
      out.write("                </div>\n");
      out.write("                 <div class=\"tech-card fade-in\">\n");
      out.write("                    <div class=\"tech-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21V3M12 3a9.004 9.004 0 00-8.716 6.747M12 3c4.805 0 8.716 3.91 8.716 8.747\" /></svg></div>\n");
      out.write("                    <h3>Web Server</h3>\n");
      out.write("                    <p>High-performance Apache Tomcat server, configured with load balancing and failover for high availability.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"tech-card fade-in\">\n");
      out.write("                    <div class=\"tech-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 16.5V9.75m0 0l-3 3m3-3l3 3M6.75 19.5a4.5 4.5 0 01-1.41-8.775 5.25 5.25 0 0110.233-2.33 3 3 0 013.758 3.848A3.752 3.752 0 0118 19.5H6.75z\" /></svg></div>\n");
      out.write("                    <h3>Cloud Infrastructure</h3>\n");
      out.write("                    <p>Deployed on secure AWS & Azure environments with auto-scaling, advanced monitoring, and disaster recovery plans.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Contact Section -->\n");
      out.write("    <section class=\"contact\" id=\"contact\">\n");
      out.write("        <div class=\"section-container\">\n");
      out.write("            <div class=\"section-header fade-in\">\n");
      out.write("                <h2>Get In Touch</h2>\n");
      out.write("                <p>Have questions about our security protocols or need a personalized demo? Reach out to our team, and we'll get back to you within 24 hours.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"contact-grid fade-in\">\n");
      out.write("                <div class=\"contact-info\">\n");
      out.write("                    <h3>Contact Information</h3>\n");
      out.write("                    <p>Our experts are available to discuss your specific needs for digital evidence management. We're here to help you build a more secure and compliant workflow.</p>\n");
      out.write("                    <ul class=\"contact-details-list\">\n");
      out.write("                        <li>\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M9.69 18.933l.003.001C9.89 19.02 10 19 10 19s.11.02.308-.066l.002-.001.006-.003.018-.008a5.741 5.741 0 00.281-.14c.186-.096.446-.24.757-.433.62-.384 1.445-.976 2.274-1.765C15.302 14.988 17 12.493 17 9A7 7 0 103 9c0 3.492 1.698 5.988 3.355 7.584a13.731 13.731 0 002.273 1.765 11.842 11.842 0 00.757.433.57.57 0 00.28.14l.018.008.006.003zM10 11.25a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z\" clip-rule=\"evenodd\" /></svg>\n");
      out.write("                            <span>123 Security Plaza, Suite 500, Tech City, 10101</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M2 3.5A1.5 1.5 0 013.5 2h1.148a1.5 1.5 0 011.465 1.175l.716 3.578a1.5 1.5 0 01-1.305 1.762l-1.104.442a1.5 1.5 0 00-1.07 2.13l3.293 3.293a1.5 1.5 0 002.13-1.07l.442-1.104a1.5 1.5 0 011.762-1.305l3.578.716A1.5 1.5 0 0118 15.352V16.5a1.5 1.5 0 01-1.5 1.5h-10A1.5 1.5 0 015 16.5v-3.865a1.5 1.5 0 01.358-1.002l.49-1.225L4.05 9.174A1.5 1.5 0 012 7.71V3.5z\" /></svg>\n");
      out.write("                            <span>+1 (555) 123-4567</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z\" /><path d=\"M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z\" /></svg>\n");
      out.write("                            <span>support@securechain.com</span>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"contact-form\">\n");
      out.write("                    <form action=\"#\" method=\"POST\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"name\">Full Name</label>\n");
      out.write("                            <input type=\"text\" id=\"name\" name=\"name\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"email\">Email Address</label>\n");
      out.write("                            <input type=\"email\" id=\"email\" name=\"email\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"message\">Your Message</label>\n");
      out.write("                            <textarea id=\"message\" name=\"message\" required></textarea>\n");
      out.write("                        </div>\n");
      out.write("                        <button type=\"submit\" class=\"submit-btn\">Send Message</button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"footer\">\n");
      out.write("        <div class=\"footer-content\">\n");
      out.write("            <div class=\"footer-section\">\n");
      out.write("                <h3>SecureChain</h3>\n");
      out.write("                <p>The gold standard in secure digital evidence management for professionals.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-section\">\n");
      out.write("                <h3>Quick Links</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#features\">Features</a></li>\n");
      out.write("                    <li><a href=\"#solutions\">Solutions</a></li>\n");
      out.write("                    <li><a href=\"#technology\">Technology</a></li>\n");
      out.write("                    <li><a href=\"#\">Security Whitepaper</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-section\">\n");
      out.write("                <h3>Company</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">About Us</a></li>\n");
      out.write("                    <li><a href=\"#\">Careers</a></li>\n");
      out.write("                    <li><a href=\"#\">Compliance</a></li>\n");
      out.write("                    <li><a href=\"#\">Press</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-section\">\n");
      out.write("                <h3>Contact Us</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <span class=\"contact-link\">\n");
      out.write("                           <svg class=\"icon-style\" style=\"width:1rem; height:1rem;\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M2 3.5A1.5 1.5 0 013.5 2h1.148a1.5 1.5 0 011.465 1.175l.716 3.578a1.5 1.5 0 01-1.305 1.762l-1.104.442a1.5 1.5 0 00-1.07 2.13l3.293 3.293a1.5 1.5 0 002.13-1.07l.442-1.104a1.5 1.5 0 011.762-1.305l3.578.716A1.5 1.5 0 0118 15.352V16.5a1.5 1.5 0 01-1.5 1.5h-10A1.5 1.5 0 015 16.5v-3.865a1.5 1.5 0 01.358-1.002l.49-1.225L4.05 9.174A1.5 1.5 0 012 7.71V3.5z\" /></svg>\n");
      out.write("                           +1 (555) 123-4567\n");
      out.write("                        </span>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"mailto:support@securechain.com\">\n");
      out.write("                            <svg class=\"icon-style\" style=\"width:1rem; height:1rem;\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z\" /><path d=\"M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z\" /></svg>\n");
      out.write("                            support@securechain.com\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-bottom\">\n");
      out.write("            <p>© 2025 SecureChain. All rights reserved. | Privacy Policy | Terms of Service</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        // All Javascript remains the same\n");
      out.write("        document.querySelectorAll('a[href^=\"#\"]').forEach(anchor => {\n");
      out.write("            anchor.addEventListener('click', function (e) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                const target = document.querySelector(this.getAttribute('href'));\n");
      out.write("                if (target) {\n");
      out.write("                    target.scrollIntoView({ behavior: 'smooth', block: 'start' });\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        const observer = new IntersectionObserver((entries) => {\n");
      out.write("            entries.forEach(entry => {\n");
      out.write("                if (entry.isIntersecting) {\n");
      out.write("                    entry.target.classList.add('visible');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }, { threshold: 0.1, rootMargin: '0px 0px -50px 0px' });\n");
      out.write("\n");
      out.write("        document.querySelectorAll('.fade-in').forEach(el => observer.observe(el));\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
