/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-07-24 04:38:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Register - SecureChain</title>\n");
      out.write("    <meta name=\"description\" content=\"Join SecureChain - Professional digital evidence management with blockchain-grade security\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            color: #374151;\n");
      out.write("            background: linear-gradient(135deg, #0d9488 0%, #15803d 50%, #0369a1 100%);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 2rem 1rem;\n");
      out.write("            position: relative;\n");
      out.write("            overflow-x: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Animated background particles */\n");
      out.write("        body::before {\n");
      out.write("            content: '';\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            background: url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 1000\"><defs><radialGradient id=\"a\" cx=\"50%\" cy=\"50%\" r=\"50%\"><stop offset=\"0%\" style=\"stop-color:rgba(255,255,255,0.15)\"/><stop offset=\"100%\" style=\"stop-color:rgba(255,255,255,0)\"/></radialGradient></defs><circle cx=\"200\" cy=\"200\" r=\"100\" fill=\"url(%23a)\"/><circle cx=\"800\" cy=\"300\" r=\"150\" fill=\"url(%23a)\"/><circle cx=\"400\" cy=\"700\" r=\"120\" fill=\"url(%23a)\"/><circle cx=\"600\" cy=\"500\" r=\"80\" fill=\"url(%23a)\"/></svg>');\n");
      out.write("            animation: float 20s ease-in-out infinite;\n");
      out.write("            z-index: -1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Floating geometric shapes */\n");
      out.write("        body::after {\n");
      out.write("            content: '';\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            background: url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 1000\"><defs><linearGradient id=\"b\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\"><stop offset=\"0%\" style=\"stop-color:rgba(255,255,255,0.1)\"/><stop offset=\"100%\" style=\"stop-color:rgba(255,255,255,0.05)\"/></linearGradient></defs><polygon points=\"100,100 200,100 150,50\" fill=\"url(%23b)\"/><polygon points=\"700,200 800,200 750,150\" fill=\"url(%23b)\"/><polygon points=\"300,600 400,600 350,550\" fill=\"url(%23b)\"/></svg>');\n");
      out.write("            animation: geometricFloat 25s ease-in-out infinite reverse;\n");
      out.write("            z-index: -1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes float {\n");
      out.write("            0%, 100% { transform: translateY(0px) rotate(0deg); }\n");
      out.write("            50% { transform: translateY(-20px) rotate(180deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes geometricFloat {\n");
      out.write("            0%, 100% { transform: translateX(0px) rotate(0deg); }\n");
      out.write("            50% { transform: translateX(10px) rotate(90deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes fadeInUp {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(30px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideIn {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateX(-20px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateX(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-container {\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\n");
      out.write("            backdrop-filter: blur(20px);\n");
      out.write("            border-radius: 24px;\n");
      out.write("            box-shadow: \n");
      out.write("                0 20px 50px rgba(0, 0, 0, 0.15),\n");
      out.write("                0 0 0 1px rgba(255, 255, 255, 0.2);\n");
      out.write("            padding: 3rem;\n");
      out.write("            max-width: 700px;\n");
      out.write("            width: 100%;\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 1;\n");
      out.write("            animation: fadeInUp 0.8s ease-out;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-container::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: -1px;\n");
      out.write("            left: -1px;\n");
      out.write("            right: -1px;\n");
      out.write("            bottom: -1px;\n");
      out.write("            background: linear-gradient(45deg, \n");
      out.write("                rgba(13, 148, 136, 0.3), \n");
      out.write("                rgba(21, 128, 61, 0.3), \n");
      out.write("                rgba(3, 105, 161, 0.3));\n");
      out.write("            border-radius: 24px;\n");
      out.write("            z-index: -1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-header {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 2.5rem;\n");
      out.write("            animation: slideIn 0.8s ease-out 0.2s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo {\n");
      out.write("            font-size: 2.2rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #0D9488;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo svg {\n");
      out.write("            width: 2.5rem;\n");
      out.write("            height: 2.5rem;\n");
      out.write("            filter: drop-shadow(0 4px 8px rgba(13, 148, 136, 0.3));\n");
      out.write("            animation: pulse 2s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes pulse {\n");
      out.write("            0%, 100% { transform: scale(1); }\n");
      out.write("            50% { transform: scale(1.05); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-header h1 {\n");
      out.write("            font-size: 2.2rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #1f2937;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            background: linear-gradient(135deg, #1f2937 0%, #0d9488 100%);\n");
      out.write("            -webkit-background-clip: text;\n");
      out.write("            -webkit-text-fill-color: transparent;\n");
      out.write("            background-clip: text;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-header p {\n");
      out.write("            color: #6b7280;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            font-weight: 400;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-grid {\n");
      out.write("            display: grid;\n");
      out.write("            gap: 1.5rem;\n");
      out.write("            animation: slideIn 0.8s ease-out 0.4s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-row {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 1fr;\n");
      out.write("            gap: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group.full-width {\n");
      out.write("            grid-column: 1 / -1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group label {\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #374151;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input,\n");
      out.write("        .form-group select,\n");
      out.write("        .form-group textarea {\n");
      out.write("            padding: 1rem 1.2rem;\n");
      out.write("            border: 2px solid #e5e7eb;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-family: inherit;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            background: white;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input:focus,\n");
      out.write("        .form-group select:focus,\n");
      out.write("        .form-group textarea:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: #0D9488;\n");
      out.write("            box-shadow: 0 0 0 4px rgba(13, 148, 136, 0.1);\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input:focus + label,\n");
      out.write("        .form-group select:focus + label,\n");
      out.write("        .form-group textarea:focus + label {\n");
      out.write("            color: #0D9488;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group textarea {\n");
      out.write("            resize: vertical;\n");
      out.write("            min-height: 90px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Input icons */\n");
      out.write("        .form-group::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            right: 1rem;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            width: 20px;\n");
      out.write("            height: 20px;\n");
      out.write("            background: url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"%23d1d5db\"><path d=\"M10 12a2 2 0 100-4 2 2 0 000 4z\"/><path fill-rule=\"evenodd\" d=\"M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z\" clip-rule=\"evenodd\"/></svg>') no-repeat center;\n");
      out.write("            opacity: 0.5;\n");
      out.write("            transition: opacity 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group:focus-within::after {\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 1.2rem;\n");
      out.write("            background: linear-gradient(135deg, #0d9488 0%, #15803d 50%, #0369a1 100%);\n");
      out.write("            color: white;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: -100%;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\n");
      out.write("            transition: left 0.5s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn:hover::before {\n");
      out.write("            left: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 15px 35px rgba(13, 148, 136, 0.4);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn:active {\n");
      out.write("            transform: translateY(-1px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error {\n");
      out.write("            color: #dc2626;\n");
      out.write("            background: linear-gradient(135deg, #fee2e2 0%, #fecaca 100%);\n");
      out.write("            padding: 1rem 1.2rem;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            border: 1px solid #fecaca;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            animation: slideIn 0.5s ease-out;\n");
      out.write("            box-shadow: 0 4px 12px rgba(220, 38, 38, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .success {\n");
      out.write("            color: #15803d;\n");
      out.write("            background: linear-gradient(135deg, #dcfce7 0%, #bbf7d0 100%);\n");
      out.write("            padding: 1rem 1.2rem;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            border: 1px solid #bbf7d0;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            animation: slideIn 0.5s ease-out;\n");
      out.write("            box-shadow: 0 4px 12px rgba(21, 128, 61, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-link {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 2rem;\n");
      out.write("            padding-top: 2rem;\n");
      out.write("            border-top: 1px solid rgba(229, 231, 235, 0.8);\n");
      out.write("            animation: slideIn 0.8s ease-out 0.6s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-link a {\n");
      out.write("            color: #0D9488;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-link a::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            bottom: -2px;\n");
      out.write("            left: 0;\n");
      out.write("            width: 0;\n");
      out.write("            height: 2px;\n");
      out.write("            background: linear-gradient(135deg, #0d9488, #15803d);\n");
      out.write("            transition: width 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-link a:hover::after {\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-link a:hover {\n");
      out.write("            color: #0f766e;\n");
      out.write("            transform: translateY(-1px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .icon-style {\n");
      out.write("            width: 1.25em;\n");
      out.write("            height: 1.25em;\n");
      out.write("            display: inline-block;\n");
      out.write("            vertical-align: -0.25em;\n");
      out.write("            fill: currentColor;\n");
      out.write("            transition: transform 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .submit-btn:hover .icon-style {\n");
      out.write("            transform: scale(1.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Enhanced form validation styles */\n");
      out.write("        .form-group input:valid {\n");
      out.write("            border-color: #10b981;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input:invalid:not(:placeholder-shown) {\n");
      out.write("            border-color: #ef4444;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Loading state */\n");
      out.write("        .loading {\n");
      out.write("            opacity: 0.7;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .loading .submit-btn {\n");
      out.write("            cursor: not-allowed;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive Design */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            body {\n");
      out.write("                padding: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .register-container {\n");
      out.write("                padding: 2rem;\n");
      out.write("                margin: 0.5rem;\n");
      out.write("                border-radius: 16px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .form-row {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .register-header h1 {\n");
      out.write("                font-size: 1.8rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .logo {\n");
      out.write("                font-size: 1.8rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .logo svg {\n");
      out.write("                width: 2rem;\n");
      out.write("                height: 2rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 480px) {\n");
      out.write("            .register-container {\n");
      out.write("                padding: 1.5rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .register-header h1 {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .form-group input,\n");
      out.write("            .form-group select,\n");
      out.write("            .form-group textarea {\n");
      out.write("                padding: 0.8rem 1rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Dark mode support */\n");
      out.write("        @media (prefers-color-scheme: dark) {\n");
      out.write("            .register-container {\n");
      out.write("                background: rgba(31, 41, 55, 0.95);\n");
      out.write("                color: #f9fafb;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .register-header h1 {\n");
      out.write("                color: #f9fafb;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .form-group label {\n");
      out.write("                color: #d1d5db;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .form-group input,\n");
      out.write("            .form-group select,\n");
      out.write("            .form-group textarea {\n");
      out.write("                background: rgba(55, 65, 81, 0.8);\n");
      out.write("                border-color: #4b5563;\n");
      out.write("                color: #f9fafb;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"register-container\">\n");
      out.write("        <div class=\"register-header\">\n");
      out.write("            <div class=\"logo\">\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                    <path fill-rule=\"evenodd\" d=\"M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z\" clip-rule=\"evenodd\" />\n");
      out.write("                </svg>\n");
      out.write("                SecureChain\n");
      out.write("            </div>\n");
      out.write("            <h1>Create Your Account</h1>\n");
      out.write("            <p>Join the secure digital evidence management platform</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form action=\"RegisterServlet\" method=\"post\">\n");
      out.write("            <div class=\"form-grid\">\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"full_name\">Full Name</label>\n");
      out.write("                        <input type=\"text\" id=\"full_name\" name=\"full_name\" value=\"");
      out.print( request.getParameter("full_name") != null ? request.getParameter("full_name") : "" );
      out.write("\" required />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"username\">Username</label>\n");
      out.write("                        <input type=\"text\" id=\"username\" name=\"username\" value=\"");
      out.print( request.getParameter("username") != null ? request.getParameter("username") : "" );
      out.write("\" required />\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"email\">Email Address</label>\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print( request.getParameter("email") != null ? request.getParameter("email") : "" );
      out.write("\" required />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"contact_number\">Contact Number</label>\n");
      out.write("                        <input type=\"tel\" id=\"contact_number\" name=\"contact_number\" pattern=\"[0-9]{7,15}\" title=\"7 to 15 digits\" value=\"");
      out.print( request.getParameter("contact_number") != null ? request.getParameter("contact_number") : "" );
      out.write("\" required />\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group full-width\">\n");
      out.write("                    <label for=\"address\">Address</label>\n");
      out.write("                    <textarea id=\"address\" name=\"address\" required>");
      out.print( request.getParameter("address") != null ? request.getParameter("address") : "" );
      out.write("</textarea>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"password\">Password</label>\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" required />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"confirm_password\">Confirm Password</label>\n");
      out.write("                        <input type=\"password\" id=\"confirm_password\" name=\"confirm_password\" required />\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"security_question\">Security Question</label>\n");
      out.write("                        <select id=\"security_question\" name=\"security_question\" required>\n");
      out.write("                            <option value=\"\">--Select a question--</option>\n");
      out.write("                            <option value=\"What is your pet's name?\" ");
      out.print( "What is your pet's name?".equals(request.getParameter("security_question")) ? "selected" : "" );
      out.write(">What is your pet's name?</option>\n");
      out.write("                            <option value=\"What is your mother's maiden name?\" ");
      out.print( "What is your mother's maiden name?".equals(request.getParameter("security_question")) ? "selected" : "" );
      out.write(">What is your mother's maiden name?</option>\n");
      out.write("                            <option value=\"What was your first car?\" ");
      out.print( "What was your first car?".equals(request.getParameter("security_question")) ? "selected" : "" );
      out.write(">What was your first car?</option>\n");
      out.write("                            <option value=\"What city were you born in?\" ");
      out.print( "What city were you born in?".equals(request.getParameter("security_question")) ? "selected" : "" );
      out.write(">What city were you born in?</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"security_answer\">Security Answer</label>\n");
      out.write("                        <input type=\"text\" id=\"security_answer\" name=\"security_answer\" required />\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"role\">Role</label>\n");
      out.write("                    <select id=\"role\" name=\"role\" required>\n");
      out.write("                        <option value=\"user\" ");
      out.print( "user".equals(request.getParameter("role")) ? "selected" : "" );
      out.write(">User</option>\n");
      out.write("          \n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"submit-btn\">\n");
      out.write("                    <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                        <path d=\"M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z\"/>\n");
      out.write("                    </svg>\n");
      out.write("                    Create Account\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        ");

            String error = (String) request.getAttribute("error");
            String message = (String) request.getAttribute("message");
            if (error != null) { 
      out.write("\n");
      out.write("                <div class=\"error\">\n");
      out.write("                    <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                        <path fill-rule=\"evenodd\" d=\"M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z\" clip-rule=\"evenodd\" />\n");
      out.write("                    </svg>\n");
      out.write("                    ");
      out.print( error );
      out.write("\n");
      out.write("                </div>\n");
      out.write("        ");
  } else if (message != null) { 
      out.write("\n");
      out.write("                <div class=\"success\">\n");
      out.write("                    <svg class=\"icon-style\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\n");
      out.write("                        <path fill-rule=\"evenodd\" d=\"M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.236 4.53L7.53 10.53a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z\" clip-rule=\"evenodd\" />\n");
      out.write("                    </svg>\n");
      out.write("                    ");
      out.print( message );
      out.write("\n");
      out.write("                </div>\n");
      out.write("        ");
  } 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"login-link\">\n");
      out.write("            Already have an account? <a href=\"login.jsp\">Sign in here</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"login-link\">\n");
      out.write("           Go to Home? <a href=\"index.jsp\">Kickoff</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        // Add smooth form interactions\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            const form = document.querySelector('form');\n");
      out.write("            const submitBtn = document.querySelector('.submit-btn');\n");
      out.write("            \n");
      out.write("            // Add loading state on form submit\n");
      out.write("            form.addEventListener('submit', function() {\n");
      out.write("                submitBtn.innerHTML = '<svg class=\"icon-style animate-spin\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><path d=\"M12 6v6l4 2\"></path></svg>Creating Account...';\n");
      out.write("                submitBtn.disabled = true;\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            // Add floating label effect\n");
      out.write("            const inputs = document.querySelectorAll('input, select, textarea');\n");
      out.write("            inputs.forEach(input => {\n");
      out.write("                input.addEventListener('focus', function() {\n");
      out.write("                    this.parentElement.classList.add('focused');\n");
      out.write("                });\n");
      out.write("                \n");
      out.write("                input.addEventListener('blur', function() {\n");
      out.write("                    if (!this.value) {\n");
      out.write("                        this.parentElement.classList.remove('focused');\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
